name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**'] # for all submitted Pull Requests

jobs:
  build-sqir:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.12'
          - '8.13'
          - '8.14'
          - '8.15'
          - '8.16'
          - '8.17'
          - 'dev'
        ocaml_version:
          - 'default'
      fail-fast: false # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v3
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-sqir.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
  build-voqc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.12'
          - '8.13'
          - '8.14'
          - '8.15'
          - '8.16'
          - '8.17'
          - 'dev'
        ocaml_version:
          - 'default'
      fail-fast: false # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v3
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-voqc.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          install : |
            startGroup "Install dependencies"
              sudo apt-get update -y -q
              opam pin add -n -y -k path coq-sqir .
              opam pin add -n -y -k path coq-voqc .
              opam update -y
              opam install --confirm-level=unsafe-yes -j 2 $PACKAGE --deps-only
            endGroup
          after_install: |
            startGroup "List installed packages"
              opam list
            endGroup


